services:
  cart-service:
    build:
      context: ./cart-service
    ports:
      - "3001:3001"
  notification-service:
    build:
      context: ./notification-service
    ports:
      - "3004:3004"
  order-service:
    build:
      context: ./order-service
    ports:
      - "3002:3002"
  payment-service:
    build:
      context: ./payment-service
    ports:
      - "3003:3003"
  product-service:
    build:
      context: ./product-service
    ports:
      - "3000:3000"
